import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../images/developer_pic.png'

export default function Home() {
	return (
		<>
			<Head>
				<title>Portfolio Frontend Developer</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main className='flex items-center text-dark w-full min-h-screen'>
				<Layout className='pt-0'>
					<div className='flex item-center justify-between w-full'>
						<div className='w-1/2'>
							<Image
								src={profilePic}
								alt='GlebovDenis'
								className='w-full h-auto'
							/>
						</div>
					</div>
				</Layout>
			</main>
		</>
	)
}
